import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "@/stores/storeProvider";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  weight: ['400', '600'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "ChatChick",
  description: "Generated by create next app",
};

const NotificationComponent = dynamic(() => import('@/components/Notification/Notification'), { ssr: false });

const MessageComponent = dynamic(() => import('@/components/Message/Message'), { ssr: false });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider >
      <html lang="en">
        <head>
          <link rel="icon" href="/chatchick.jpg" />
        </head>
        <body className={`${inter.className} ${poppins.className}`}>
          <NotificationComponent>
            <MessageComponent>
              {children}
            </MessageComponent>
          </NotificationComponent>
        </body>
      </html>
    </StoreProvider>
  );
}
